#!/usr/bin/python3
"""Factorize the numbers in the file to be the result of multiplying two small numbers together"""
from sys import argv


def factorize(number):
    """Find two little numbers that you can multiply together to get a certain number!"""
    j = 2

    if number < 2:
        return
   
    while number % j:
        j += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number, number / j, j))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
