#!/usr/bin/python3
from sys import argv


def factorize(num):
    j = 2

    if num < 2:
        return
   
    while num % j:
        j += 1
    print("{:.0f}={:.0f}*{:.0f}".format(num, num / j, j))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            num = int(line.split('\n')[0])
            factorize(num)
            line = file.readline()
except:
    pass
